### ISSUE TITLE
Sharing iP code quality check results [for @GanapathySanathBalaji]

### ISSUE THREAD

**Issue by nus-pe-script** [GanapathySanathBalaji/duke#1]
We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most one example is given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/duke/task/Task.java` line `22`](https://github.com/GanapathySanathBalaji/duke/blob/74561f13760c51f3501d694bddf7b340a80b9392/src/main/java/duke/task/Task.java#L22):
```java
    // tick -> Task is done ;  X symbol -> Task isn't done ;
``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1:

**Comment by GanapathySanathBalaji** [comment]
Thanks for the analysis.
